### ISSUE TITLE
Evaluate: Switch to SonarCloud GitHub Action

### ISSUE THREAD

**Issue by babisRoutis** [eu-digital-identity-wallet/eudi-lib-kmp-statium#9]
**Current Problem**  
Using Sonar Gradle plugin complicates our build and doesn't handle KMP sources optimally.

**Solution**  
Replace with official [SonarCloud GitHub Action](https://github.com/SonarSource/sonarcloud-github-action).

**Key Benefits**:
- ✅ Better KMP support (all source sets included)
- ✅ Faster analysis (decoupled from build)
- ✅ Simpler config (single YAML file)
- ✅ Keeps existing Kover setup
- Removes sonar plugin dependency from gradle

**No Changes Needed**:
- Existing `SONAR_TOKEN` works
- Same project key/metrics
- Current Kover config stays

Indicative implementation

```yaml
ame: SonarCloud Analysis for KMP with Kover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and generate Kover reports
        run: |
          ./gradlew koverMergedXmlReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=eu-digital-identity-wallet_eudi-lib-kmp-statium
            -Dsonar.organization=eu-digital-identity-wallet
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/kover/merged/xml/report.xml
            -Dsonar.kotlin.coverage.reportPaths=build/reports/kover/merged/xml/report.xml
            -Dsonar.sources=lib/src/commonMain,lib/src/jvmMain,lib/src/jvmAndAndroidMain
            -Dsonar.tests=lib/src/commonTest,lib/src/jvmTest,lib/src/jvmAndAndroidTest
            -Dsonar.java.binaries=build/classes/kotlin/jvm,lib/build/classes/kotlin/jvm
            -Dsonar.kotlin.binaries=build/classes/kotlin/jvm,lib/build/classes/kotlin/jvm
            -Dsonar.language=kotlin
            -Dsonar.kotlin.multiplatform.reportPaths=build/reports/kover/merged/xml/report.xml
            -Dsonar.exclusions=**/build/**,**/.gradle/**,**/*.kts,**/generated/**
            -Dsonar.test.exclusions=**/build/**,**/.gradle/**
            -Dsonar.projectBaseDir=${{ github.workspace }}
```
